name: ValidateYaml

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      displayName: Install Dependencies
    - name: Kubeval
      displayName: Get New Changes 
      uses: stefanprodan/kube-tools@v1.2.0
      displayName: Validate the YAML file(s)
      with:
        kubectl: 1.16.2
        kustomize: 3.4.0
        helm: 2.16.1
        helmv3: 3.0.0
        command: |
          echo "Run kubeval"
          kubeval -d Policies --strict --ignore-missing-schemas
        
